Fix bug when choosing occupied square
Summary:
I noticed that the program crashes if the user choose an invalid move: it turns out that `promptUserForValidMove` forgot to check whether the user's move is valid (it only checks if the move parses).

I fixed this by adding a check to `state.moveAllowed` in the move-validation loop.

[NOTE: in the real world, if I hadn't already merged the relevant commit to production (in this case, the commit that created the bug in `promptUserForValidMove`), I would amend that commit instead and force-push an updated version to GitHub (this is my preferred workflow). However, if I had already had my PR approved and merged it to production, then I would make a bug-fix commit like this]

Test plan:

Before:
```
$ ts-node src/main.ts

   A   B   C
1    |   |
  -----------
2    |   |
  -----------
3    |   |
Make a move (e.g. A2): A1

   A   B   C
1  O |   |
  -----------
2    |   |
  -----------
3    |   |
Make a move (e.g. A2): A1
[...]/tic-tac-toe/src/game-state.ts:48
      throw new Error("Can't choose a space that's already taken.");
            ^
Error: Can't choose a space that's already taken.
[...]
```

After:
```
$ ts-node src/main.ts

   A   B   C
1    |   |
  -----------
2    |   |
  -----------
3    |   |
Make a move (e.g. A2): A1

   A   B   C
1  O |   |
  -----------
2    |   |
  -----------
3    |   |
Make a move (e.g. A2): A1
Please enter a valid move (e.g. A2): A2

   A   B   C
1  O |   |
  -----------
2  X |   |
  -----------
3    |   |
Make a move (e.g. A2):
```